project:
  type: website

website:
  title: "Carlos Granell"
  description: "Carlos Granell is a GIScience researcher and open science and reproducibility advocate"
  site-url: "https://cgranell.github.io/"
  repo-url: "https://github.com/cgranell/cgranell.github.io"
  reader-mode: true

  page-footer:
    left: "[cgranell.github.io](https://cgranell.github.io/)"
    right:
    - text: "License"
      href: LICENSE

  navbar:
    logo: images/marca-uji-negre.jpg
    logo-alt: "Universitat Jaume I"
    
    left:
      - href: index.qmd
        text: Home
      - href: papers
        text: Papers
      - href: teaching
        text: Teaching
      - href: outreach
        text: Outreach
      - href: extras
        text: Extras
  
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    toc-depth: 3
    toc-float: true
    toc-smooth-scroll: true


