project:
  type: website

website:
  title: "Carlos Granell"
  description: "Carlos Granell is a GIScience researcher and open science and reproducibility advocate"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: papers
        text: Papers
      - href: teaching
        text: Teaching
      - href: outreach
        text: Outreach
      - href: extras
        text: Extras

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    toc-depth: 3
    toc-float: true
    toc-smooth-scroll: true


