---
title: Research
title-block-banner: true
---

## Research perspective

Doing research is exciting and challenging. That's true. If you join a research team, it's worth asking yourself [how you do your research](http://www.cs.virginia.edu/~robins/YouAndYourResearch.html). This is not a trivial question when researchers are continuously frustated by [bureaucracy](https://doi.org/10.1371/journal.pbio.1000197) and [evaluation metrics](https://medium.com/confessions-of-a-re-tired-academic/i-wasnt-very-productive-if-you-believe-the-numbers-game-d6232332f73d) (how many high-impact papers, how many citations, etc) that can interfere in the real objective of research: *improving people's lives and making the world a better place*.

Research is no longer an individual task. If you think you can tackle society's major challenges on your own, you are mistaken. Doing science involves cooperating and communicating with others:
talk to your office mates, coverse with colleagues in person or remotedly, and expand your network whenever you can. You never know when inspiration might strike.

To quote Richard Hamming, "The closed door is symbolic of a closed mind." In his [talk](http://www.cs.virginia.edu/~robins/YouAndYourResearch.html), Hamming observed that *"if you have the door to your office closed, you get more work done today and tomorrow, and you are more productive than most. But 10 years later somehow you don't know quite know what problems are worth working on; all the hard work you do is sort of tangential in importance. He who works with the door open gets all kinds of interruptions, but he also occasionally gets clues as to what the world is and what might be important."* So why not try to follow this simple rule: ["Leave Your Door Open"](https://doi.org/10.1371/journal.pcbi.0030213).

A research team is a collaborative environment with its own dynamics. It's wonderful when you work effectively to develop creative and innovative solutions that improve people's quality of life, but, most importantly, you are part of a group and should help ensure the well-being and healthy relationships of the team members and colleagues. Remember: in science, the whole is greater than the sum of the parts.


## Research interests

My research interests are in the areas of GIScience, urban computing, and open science and reproducibility practices in GIScience.


### GIScience

What is Geographic Information Science (GIScience)? What does conducting research in this field entail?

Today, performing geospatial analysis is easier than ever, thanks to the abundance of open-source geospatial tools and frameworks, as well as access to vast volumes of geospatial data and products. However, greater ease of access does not automatically lead to a better understanding. The current challenge facing GIScience is encapsulated in the following question: *what type of spatiotemporal question is being posed, which methods and models are appropriate for answering it, and why?* Since different questions require different methods, GIScience should be understood as a *metascience* dedicated to the practice of designing, using, and justifying geographic information methods and models to answer various types of spatiotemporal questions; questions that are often framed within the context of specific application domains. Within this frame, my work encompasses geospatial data science, GeoAI, spatial analysis and visualization, and geospatial data integration, while always emphasising the critical evaluation of the use and validity of geospatial methods, questions, and results, wheter in research or teaching.

### Urban computing

The use of computing and geospatial technologies to address urban problems, such as mobility, transport, aging population, environmental health, and education.

### Open science and reproducibility practices in GIScience 

Reuse, reproducibility, replicability, transparency, openness, integrity, ethics – all in the context of computational research on geospatial data.



## Readings for good practices in (sustainable and green) research

### Ten simple rules series

- [Ten Simple Rules for Doing Your Best Research, According to Hamming](https://doi.org/10.1371/journal.pcbi.0030213)
- [Ten Simple Rules for Reviewers](https://doi.org/10.1371/journal.pcbi.0020110)
- [Ten Simple Rules for Graduate Students](https://doi.org/10.1371/journal.pcbi.0030229)
- [Ten Simple Rules for a Successful Collaboration](https://doi.org/10.1371/journal.pcbi.0030044)
- [Ten Simple Rules for Getting Grants](https://doi.org/10.1371/journal.pcbi.0020012)
- [Ten Simple Rules for Getting Published](https://doi.org/10.1371/journal.pcbi.0010057)
- [Ten Simple Rules for Providing a Scientific Web Resource](https://doi.org/10.1371/journal.pcbi.1000517)
- [Ten Simple Rules for Chairing a Scientific Session](https://doi.org/10.1371/journal.pcbi.1000517)
- [Ten Simple Rules To Combine Teaching and Research](https://doi.org/10.1371/journal.pcbi.1000358)
- [Ten Simple Rules for Making Good Oral Presentations](https://doi.org/10.1371/journal.pcbi.0030077)

And more in the [Ten Simple Rules collection](https://collections.plos.org/ten-simple-rules).

### Other readings

- [Real Lives and White Lies in the Funding of Scientific Research](http://www.plosbiology.org/article/info%3Adoi%2F10.1371%2Fjournal.pbio.1000197)
- [Science 2.0 (change will happen..)](http://firstmonday.org/htbin/cgiwrap/bin/ojs/index.php/fm/article/view/2961/2573)
- [Digging into data using new collaborative infrastructures supporting humanities-based computer science research](http://firstmonday.org/htbin/cgiwrap/bin/ojs/index.php/fm/article/view/3372/2950)
- [How college students use the Web to conduct everyday life research](http://firstmonday.org/htbin/cgiwrap/bin/ojs/index.php/fm/article/view/3484/2857)
- [How to build a bad Research Center](http://cacm.acm.org/magazines/2014/3/172507-how-to-build-a-bad-research-center/abstract)
- [Data sharing and how it can benefit your scientific career](https://www.nature.com/articles/d41586-019-01506-x)
- [Ways to give an effective seminar about your research project](https://www.nature.com/articles/d41586-019-01574-z)
- [Toolkit: How to write a great academic CV](https://www.nature.com/articles/d41586-019-01358-5)
- [Scientific presentations: A cheat sheet](http://blogs.nature.com/naturejobs/2017/01/11/scientific-presentations-a-cheat-sheet/)
- [How to give a great scientific talk](https://www.nature.com/articles/d41586-018-07780-5)
- [Look beyond publications in assessment of PhDs](https://www.nature.com/articles/s41562-019-0763-7)

### Be green

- [Green Books Publisher](http://www.greenbooks.co.uk/)
- Sep 2019, [Seven steps to make travel to scientific conferences more sustainable](https://www.nature.com/articles/d41586-019-02747-6)
- May 2019, [As a climate researcher, should I change my air-travel habits?](https://www.nature.com/articles/d41586-019-01652-2)
- Apr 2013, [Hypocrites in the air: should climate change academics lead by example?](http://kevinanderson.info/blog/hypocrites-in-the-air-should-climate-change-academics-lead-by-example/)
