---
title: "Extras"
---

## Forthcoming trips/events

- **Brighton, UK (22-25 Jun 2026)**. [ACM Interaction Design and Children (IDC)](https://idc.acm.org/2026/) conference.
- **Tartu, Estonia (16-19 Jun 2026)**. [AGILE 2026](https://www.agile-online.org/) conference.
- **(Virtual) Basel, Switzerland (8-10 Jun 2026)**. [GeoPython 2026](https://2026.geopython.net/) conference.
- **Barcelona, Spain (13-15 Apr 2026)**. [ACM CHI 2026](https://chi2026.acm.org/) conference.

## Past trips/events

- **Virtual (Tartu, Estonia, 2-4 Mar 2026)**. [AGILE Council meeting](https://www.agile-online.org/).
- **Virtual (23 Jan 2026)**. [AGILE Council meeting](https://www.agile-online.org/).

---

- **Utrecht, The Netherlands (6-8 Oct 2025)**. [AGILE Council meeting](https://www.agile-online.org/).
- **Barcelona, Lyon, Strasbourg, Luxembourg, Paris (4-15 Aug 2025)**. Interrail family trip.
- **Virtual (8-9 Jul 2025)**. [SpaceSUITE project meeting](https://www.spacesuite-project.eu/).
- **Dresden, Germany (10-13 Jun 2025)**. [AGILE 2025](https://www.agile-online.org/) conference.
- **Cagliari, Italy (14-26 May 2025)**. EM master preparation meeting.
- **Albarracín, Spain (17-20 Mar 2025)**. Family trip.
- **Dresden, Germany (10-12 Mar 2025)**. [AGILE Council meeting](https://www.agile-online.org/).
- **(Virtual) Basel, Switzerland (24-26 Feb 2025)**. [GeoPython 2025](https://2025.geopython.net/) conference.
- **Firenze/Pisa, Italy (31 Jan-3 Feb 2025)**. Family trip.

---

- **Salzburg, Austria (4-6 Dec 2024)**. [SpaceSUITE project meeting](https://www.spacesuite-project.eu/).
- **Würzburg, Germany (30 Sep - 2 Oct 2024)**. [AGILE Council meeting](https://www.agile-online.org/).
- **Tallinn, Estonia (3-5 Jul 2024)**. [SpaceSUITE project meeting](https://www.spacesuite-project.eu/).
- **Glasgow, UK (4-7 Jun 2024)**. [AGILE 2024](https://www.agile-online.org/) conference.
- **Glasgow, UK (3-7 Apr 2024)**. [AGILE Council meeting](https://www.agile-online.org/).

---

- **Valencia, Spain (2-4 Oct 2023)**. [AGILE Council meeting](https://www.agile-online.org/).
- **Delft, The Netherlands (13-16 Jun 2023)**. [AGILE 2023](https://www.agile-online.org/) conference.
- **Delft, The Netherlands (3-6 Apr 2023)**. [AGILE Council meeting](https://www.agile-online.org/).
- **Tartu, Estonia (12-17 Mar 2023)**. Reproducibility in GIS/Geoinformatics course at [University of Tartu](https://landscape-geoinformatics.ut.ee/home-0?lang=en).

---

- **Castellón, Spain (6 Oct 2022)**. [AGILE Council meeting](https://www.agile-online.org/).
- **Virtual (20-23 Jun 2022)**. [useR! 2022](https://user2022.r-project.org/) The R User Conference.
- **Vilnius, Lithuania (14-17 Jun 2022)**. [AGILE 2022](https://www.agile-online.org/) conference.
- **Vilnius, Lithuania (Mar 31 - Apr 1 2022)**. [AGILE Council meeting](https://www.agile-online.org/).

---

- **Virtual (13-14 Dec 2021)**. [Spatial Data Science Symposium 2021](http://wp1066709.server-he.de/sdss2021/index.html).
- **~~Würzburg, Germany~~ virtual (20-21 Oct 2021)**. [AGILE Council meeting](https://www.agile-online.org/).
- **~~Poznań, Poland~~ virtual (27-30 Sep 2021)**. [GIScience 2021](https://www.giscience.org/) conference.
- **~~Valencia, Spain~~ virtual (7-9 Jul 2021)**. [JENUI 2021](https://jenui2021.uv.es/).
- **Virtual (6-9 Jul 2021)**. [useR! 2021](https://user2021.r-project.org/) The R User Conference.
- **~~Chania, Crete, Greece~~ virtual (8-11 Jun 2021)**. [AGILE 2021](https://www.agile-online.org/) conference.
- **~~Girona, Spain~~ virtual (24-25 Mar 2021)**. [SIG Libre 2021](https://www.jornadassiglibre.org/).
- **~~Chania, Crete, Greece~~ virtual (5 Mar 2021)**. [AGILE Council meeting](https://www.agile-online.org/).
- **Virtual (21 Jan 2021)**. [rstudio::global 2021](https://rstudio.com/conference/) conference.

---

- **~~Gainesville, FL, USA~~ virtual (18-19 Nov 2020)**. [Research Reproducibility 2020](https://pwd.aa.ufl.edu/researchre-pro/).
- **~~Tromso, Norway~~ virtual (18-19 Nov 2020)**. [15th Munin Conference on Scholarly Publishing](https://site.uit.no/muninconf/program/).
- **~~Augsburg, Germany~~ virtual (8 Oct 2020)**. [AGILE Council meeting](https://www.agile-online.org/).
- **~~Valencia, Spain~~ virtual (8-10 Jul 2020)**. [JENUI 2020](https://jenui2020.uv.es/).
- **~~Milano, Italy~~ virtual (17-20 June 2020)**. [eRum 2020](https://2020.erum.io/) conference.
- **~~Chania, Crete, Greece~~ virtual (Mar 2020)**. [AGILE Council meeting](https://www.agile-online.org/).

---

- **Nottingham, UK (14-16 Oct 2019)**. [AGILE Council meeting](https://www.agile-online.org/).
- **Liverpool, UK (23-27 Sep 2019)**. Erasmus+ mobility grant, 1-week stay at [Geographic Data Science Lab](https://www.liverpool.ac.uk/geographic-data-science/), University of Liverpool.
- **Fredericton, Canada (1 Jul - 15 Aug 2019)**. Research visit at [Monica's lab](https://www.people-in-motion-lab.org/), University of New Brunswick.
- **Limassol, Cyprus (17-20 Jun 2019)**. [AGILE 2019](https://www.agile-online.org/) conference.
- **Delft, The Netherlands (31 Mar - 2 Apr 2019)**. [AGILE Initiative](https://o2r.info/reproducible-agile/initiative/) expert meeting.
- **Limassol, Cyprus (13-15 Mar 2019)**. [AGILE Council meeting](https://www.agile-online.org/).

---

- **Lisbon, Portugal (28-30 Nov 2018)**. [GEO-C](http://www.geo-c.eu) theses defenses.
- **Athens, Greece (23-25 Oct 2018)**. [AGILE Council meeting](https://www.agile-online.org/).
- **Lugano, Switzerland (9-11 Oct 2018)**. [OGRS 2018](http://2018.ogrs-community.org/).
- **Lisbon, Portugal (4-6 Oct 2018)**. [H2020-MSCA-ITN-2019](https://ec.europa.eu/research/mariecurieactions/about/innovative-training-networks_en) proposal writing meeting.
- **Barcelona, Spain (17-18 Sep 2018)**. [Campus Gutenberg-CosmoCaixa 2018](https://gutenberg.bsm.upf.edu/).
- **Valencia, Spain (24 Jul 2018)**. [IGARSS 2018](http://www.igarss2018.org/).
- **Guimarães, Portugal (16-21 Jul 2018)**. [FOSS4G-Europe 2018](https://foss4g-europe.osgeopt.pt/) (& family trip to Oporto, Braga, Guimarães).
- **Barcelona, Spain (4 Jul 2018)**. [JENUI 2018](http://jenui2018.uoc.edu/) conference.
- **Madrid, Spain (28 Jun 2018)**. Jornadas de Seguimiento RyC Intermedio.
- **Lund, Sweden (12-15 Jun 2018)**. [AGILE 2018](https://www.agile-online.org/) conference.
- **Ericeira, Portugal (13-17 May 2018)**. [GEO-C Catalyst event](http://geo-c.eu/).
- **Adanero, Spain (Apr 2018)**. Easter holiday (Avila, Segovia, Cuellar, Medina del Campo).

---

- **Amsterdam, the Netherlands (15-18 Oct 2017)**. [ACM CHIPLAY 2017](http://chiplay.acm.org/).
- **Lisbon, Portugal (13 Oct 2017)**. [GEO-C](http://geo-c.eu/) SB and EB meetings.
- **Muenster, Germany (27-28 Sep 2017)**. [H2020-MSCA-ITN-2018](https://ec.europa.eu/research/mariecurieactions/about/innovative-training-networks_en) proposal writing meeting.
- **Salzburg, Austria (4-7 Jul 2017)**. [GI_Forum 2017](http://www.gi-forum.org/) conference (& family trip to Vienna, Graz and Salzburg).
- **Funchal, Portugal (20-22 Jun 2017)**. Workshop on [Playable Cities](http://www.intetain.org/2017/show/playable-cities) (& family trip).
- **Wageningen, the Netherlands (9-12 May 2017)**. [AGILE 2017](https://agile-online.org/index.php/conference/conference-2017) conference.
- **Milano, Italy (3-4 Apr 2017)**. [FP7-ERMES](http://www.ermes-fp7space.eu/) final review meeting.
- **Lisbon, Portugal (1 Mar 2017)**. [Erasmus Mundus Master GeoTech](http://mastergeotech.info/) thesis defenses.
- **Muenster, Germany (21-23 Feb 2017)**. [GEO-C](http://geo-c.eu/) SB and EB meetings, and mid-term project review meeting.

---

- **Castellón, Spain (23 Nov 2016)**. [Workshop on writing Impact section in H2020 proposals](http://ruvid.org/ri-world/events/taller-de-preparacion-de-la-seccion-impacto-en-proyectos-colaborativos-h2020-castellon/).
- **Lisbon, Portugal (10-11 Oct 2016)**. [GEO-C](http://geo-c.eu/) EB Meeting (online attendance).
- **Barcelona, Spain (6 Oct 2016)**. [ERC 2017 Info day and CoG proposal preparation workshop](http://agaur.gencat.cat/en/detalls/activitatagenda/Jornada-ERC).
- **Lanzarote, Canary Islands, Spain (Jul 2016)**. 1-week holiday in Lanzarote island.
- **Madrid, Spain (4 Jul 2016)**. [ERC StG/CoG 2017 workshop](http://www.eshorizonte2020.es/ciencia-excelente/consejo-europeo-de-investigacion-erc/eventos/jornada-informativa-convocatorias-2017-del-consejo-europeo-de-investigacion-erc).
- **Sesimbra, Portugal (9-13 May 2016)**. [GEO-C retreat](http://geo-c.eu/).
- **Salzburg, Austria (18-22 Apr 2016)**. Erasmus+ mobility grant, 1-week stay at [Department of Geoinformatics - Z_GIS](http://www.zgis.at/index.php/en/), University Salzburg.
- **Madrid, Spain (17-18 Feb 2016)**. [OpenCityData](http://opencitydata.es/) project meeting.
- **Muenster, Germany (1-3 Feb 2016)**. [Erasmus Mundus Master GeoTech](http://mastergeotech.info/) thesis defenses and [GEO-C](http://geo-c.eu/) EB meeting.

---

- **Antwerpen, Belgium (27 Dec 2015 - 3 Jan 2016)**. 1-week holiday in Belgium (Antwerpen, Brussels, Ghent, Brugge).
- **Barcelona, Spain (23 Nov 2015)**. [Novatica's special issue presentation](http://www.ati.es/spip.php?article2813).
- **Barcelona, Spain (18 Nov 2015)**. [Smart City Expo World Congress](http://www.smartcityexpo.com/en/).
- **Mexico City, Mexico (7-12 Nov 2015)**. [GEO-XII Plenary & Citizen GEOSS Side Event](http://www.earthobservations.org/geo12.php).
- **Milano, Italy (21-24 Sep 2015)**. [FP7-ERMES](http://www.ermes-fp7space.eu/) mid-term review meeting.
- **Barcelona, Spain (16 Sep 2015)**. [ERC StG/CoG 2016 workshop](http://www10.gencat.cat/agaur_web/AppJava/catala/a_esdeveniment.jsp?idesdeveniment=2641).
- **Castellón, Spain (14-25 Sep 2015)**. [GEO-C orientation Camp & Teaching event](http://geo-c.eu).
- **Como, Italy (14-17 Jul 2015)**. [FOSS4G-Europe 2015](http://europe.foss4g.org/2015/) conference.
- **Copenhagen, Denmark (15-16 Jun 2015)**. [9th GEO European Projects' Workshop](http://geo.pbe.eea.europa.eu/).
- **Lisbon, Portugal (9-10 Jun 2015)**. [AGILE 2015](http://www.agile-online.org/index.php/conference/conference-2015) conference.
- **Lisbon, Portugal (7-9 Jun 2015)**. [GEO-C](http://geo-c.eu/) Open City Toolkit workshop & selection workshop.
- **Muenster, Germany (16-17 Apr 2015)**. [GEO-C](http://geo-c.eu/) Open City Toolkit meeting.
- **Madrid, Spain (8 Apr 2015)**. PhD committee member.
- **Valencia, Spain (26-27 Mar 2015)**. [FP7-ERMES](http://www.ermes-fp7space.eu/) project meeting.
- **Valencia, Spain (5-6 Mar 2015)**. [GEO-C](http://geo-c.eu/) KoM project meeting.
- **Tarragona, Spain (26-30 Jan 2015)**. [Winter School on Big Data 2015](http://grammars.grlmc.com/bigdat2015/).

---

- **Castellón, Spain (3-6 Jun 2014)**. [AGILE 2014](http://www.agile-online.org/index.php/conference/conference-2014) conference.
- **Brussels, Belgium (21 May 2014)**. ERC recruitment process.
- **Ispra, Italy (20-21 Mar 2014)**. Emerging ICT for Citizens' "Veillance" workshop.
- **Milano, Italy (12-13 Mar 2014)**. [FP7-ERMES](http://www.ermes-fp7space.eu/) KoM project meeting.
- **Brussels, Belgium (25 Feb 2014)**. ERC recruitment process.
- **Ispra, Italy (5-7 Feb 2014)**. [Citizens' Science & Smart Cities Summit](http://ies.jrc.ec.europa.eu/DE/derdu-latest-news/sdi-workshops/citizens-science-and-smart-cities-summit.html).

---

- **Ispra, Italy (23 Sep 2013)**. [Air quality & citizen quality of life indicators workshop](http://ies.jrc.ec.europa.eu/DE/derdu-latest-news/sdi-workshops/air-quality-and-citizen-quality-of-life-indicators.html).
- **Barcelona, Spain (16-17 Sep 2013)**. UPF visit.
- **Brussels, Belgium (27-28 Aug 2013)**. [EnviroFI](http://www.envirofi.eu/) final project review.
- **Valladolid, Spain (16 Jul 2013)**. PhD committee member.
- **Florence, Italy (23-27 Jun 2013)**. [INSPIRE 2013 conference](http://inspire.jrc.ec.europa.eu/events/conferences/inspire_2013/).
- **Dublin, Ireland (4-8 Mar 2013)**. [Dublin Conferences Week](http://eurogi.org/2013-dublin-conferences.html) & [EnviroFI](http://www.envirofi.eu/) project meeting & 3rd AB meeting.
- **Florence, Italy (20-22 Jan 2013)**. [EnviroFI](http://www.envirofi.eu/) project meeting.

---

- **Oslo, Norway (18-21 Sep 2012)**. [EnviroFI](http://www.envirofi.eu/) project meeting & EnviroFII proposal meeting.
- **Vienna, Austria (23-26 Apr 2012)**. [EnviroFI](http://www.envirofi.eu/) project meeting, 2nd stakeholder consultation workshop & 2nd AB meeting.
- **Karlsruhe, Germany (21-23 Feb 2012)**. [EnviroFI](http://www.envirofi.eu/) WP4-5 technical meeting.

---

- **Ispra, Italy (25-27 Oct 2011)**. [EuroGEOSS](http://www.eurogeoss.eu/) project meeting.
- **Ispra, Italy (5-7 Oct 2011)**. [EnviroInfo 2011](http://www.ec-gis.org/Workshops/EnviroInfo2011/) & 1st stakeholder consultation workshop.
- **Ispra, Italy (3-4 Oct 2011)**. [EnviroFI](http://www.envirofi.eu/) project meeting.
- **Madrid, Spain (12-14 Jul 2011)**. [EnviroFI](http://www.envirofi.eu/) project meeting.
- **Ispra, Italy (16-18 May 2011)**. [EuroGEOSS](http://www.eurogeoss.eu/) project meeting.
- **Ispra, Italy (16 Mar 2011)**. 3-year postdoc researcher at IES, EC-JRC.
- **Lisbon, Portugal (Mar 2011)**. [Erasmus Mundus Master GeoTech](http://mastergeotech.info/) thesis defenses.

---

- **Lisbon, Portugal (27-29 Oct 2010)**. [I Jornadas Ibéricas de Infraestructuras de Datos Espaciales (JIIDE)](http://www.usig.pt).
- **Castellón, Spain (22-23 Oct 2010)**. [GeoMundus 2010](http://geomundus.uji.es/).
- **Toledo, Spain (Oct 2010)**. Weekend holiday.
- **Dubrovnik, Croatia (Aug 2010)**. 1-week holiday south Croatia (Dubrovnik, Korcula, Ston, Mostar).
- **Madrid, Spain (30 Jun - 1 Jul 2010)**. [EV meeting](http://www.espanavirtual.org/).
- **Krakow, Poland (22-25 Jun 2010)**. [INSPIRE 2010](http://inspire.jrc.ec.europa.eu/events/conferences/inspire_2010/).
- **Krakow, Poland (22-25 Jun 2010)**. [EuroGEOSS](http://www.eurogeoss.eu/) and [eSDI-Net+](http://www.esdinetplus.eu/) project meetings.
- **Guimarães, Portugal (11-14 May 2010)**. [AGILE 2010](http://agile2010.dsi.uminho.pt/).
- **Ispra, Italy (10-12 May 2010)**. [EuroGEOSS](http://www.eurogeoss.eu/) project meeting.
- **Barcelona, Spain (Apr 2010)**. [IDEE WG on SDI Observatory](http://www.idee.es/show.do?to=pideep_subgrupo_trabajo.ES).
- **Darmstadt, Germany (Mar 2010)**. [eSDI-Net+](http://www.esdinetplus.eu/) project meeting.
- **Girona, Spain (Mar 2010)**. [IV Jornadas SIG Libre 2010](http://www.sigte.udg.es/jornadassiglibre/).
- **Lisbon, Portugal (Mar 2010)**. [Erasmus Mundus Master GeoTech](http://mastergeotech.info/) thesis defenses.
- **Madrid, Spain (Feb 2010)**. [IDEE WG meeting](http://www.cchs.csic.es/sig/ReunionNacionalIDEE/index.php).
- **St. Maarten, Netherlands Antilles (Feb 2010)**. [GEOProcessing 2010 Conference](http://www.iaria.org/conferences2010/GEOProcessing10.html).
- **Muenster, Germany (Feb 2010)**. [Erasmus Mundus Master GeoTech](http://mastergeotech.info/) thesis defenses.
- **Nottingham, UK (Jan 2010)**. [EuroGEOSS](http://www.eurogeoss.eu/) WP2 working meeting.

---

- **Turin, Italy (Nov 2009)**. [European SDI Best Practice Award 2009 Conference (eSDI-Net+)](http://www.esdinetplus.eu/get_involved/award_2009.html).
- **Ispra, Italy (Oct 2009)**. [EuroGEOSS](http://www.eurogeoss.eu/) project meeting.
- **Nottingham, UK (Sep-Dec 2009)**. Research visit at [CGS](http://www.nottingham.ac.uk/cgs/).
- **San Diego (CA), USA (Jul 2009)**. [ESRI UC 2009](http://www.esri.com/events/uc/index.html).
- **Rotterdam, The Netherlands (Jun 2009)**. [GSDI conference](http://gsdi.org/gsdi11/) and [INSPIRE conference](http://inspire.jrc.ec.europa.eu/events/conferences/inspire_2009/).
- **Hanover, Germany (Jun 2009)**. [AGILE 2009](http://www.agile2009.de).
- **Leuven, Belgium (Mar 2009)**. [eSDI-Net+](http://www.esdinetplus.eu/) project meeting.
- **Madrid, Spain (Feb 2009)**. [EV meeting](http://www.espanavirtual.org/).
- **Muenster, Germany (Feb 2009)**. [Erasmus Mundus Master GeoTech](http://mastergeotech.info/) thesis defenses.
- **Lisbon, Portugal (Feb 2009)**. [eSDI-Net+ Iberian workshop](http://sites.google.com/site/esdinetpt/Home) and GTIDEE meeting.
- **Madrid, Spain (Jan 2009)**. [EV meeting](http://www.espanavirtual.org/).

---

- **Valencia, Spain (Dec 2008)**. [OGC Technical Meeting](http://www.opengeospatial.org/event/0812tc) and [GEOSS Architecture XXV workshop](http://www.ogcnetwork.net/node/391).
- **Tenerife, Spain (Nov 2008)**. [JIDEE 2008](http://www.jidee08.org/).
- **Maribor, Slovenia (Jun 2008)**. [INSPIRE 2008 Conference](http://www.ec-gis.org/Workshops/inspire_2008/index.cfm).
- **Milano, Italy (Jun 2008)**. Final review of EU Project [AWARE](http://www.aware-eu.info).
- **Nottingham, UK (Jun 2008)**. [Geospatial Web Services Workshop 2008](http://www.nottingham.ac.uk/geography/geowebservices/).
- **Girona, Spain (May 2008)**. [AGILE 2008](http://www.agile2008.es/) Conference.
- **Girona, Spain (Mar 2008)**. [II Jornadas SIG Libre 2008](http://www.sigte.udg.es/jornadassiglibre/).

---

- **Vilamoura, Algarve, Portugal (Nov 2007)**. OTM Conference - [SWWS 2007](http://www.cs.rmit.edu.au/fedconf/index.html?page=swws2007cfp) Workshop.
- **Santiago de Compostela, Spain (Oct 2007)**. [JIDEE 2007](http://www.jidee07.org/).
- **Darmstadt, Germany (Sep 2007)**. [eSDI-Net+](http://www.esdinetplus.eu/) Kick-off meeting.
- **Fontainemore, Val d'Aosta, Italy (Jul 2007)**. [AWARE](http://www.aware-eu.info) meeting.
- **Bolzano, Italy (Jun 2007)**. [27th EARSel Symposium: Geoinformation in Europe](http://www.earsel.org).
- **Aalborg, Denmark (May 2007)**. [AGILE 2007](http://www.agile-online.org/) Conference.

---

- **Milano, Italy (Nov 2006)**. [AWARE](http://www.aware-eu.info) working session.
- **Castellón, Spain (Oct 2006)**. [JIDEE 2006](http://jidee06.uji.es).
- **French Provence (Aug 2006)**. 5-day holidays through Arles, Nimes, Aix en Provence, Avignon, etc.
- **Fiesole/Firenze, Italy (Jul 2006)**. [Vespucci Summer Institute](http://www.vespucci.org).
- **Innsbruck, Austria (Jun 2006)**. [12th EC-GI & GIS Workshop](http://www.ec-gis.org/Workshops/12ec-gis/).
- **Benicassim/Castellón, Spain (Jun 2006)**. [AWARE](http://www.aware-eu.info) meeting.
- **Milano, Italy (Apr 2006)**. [AWARE](http://www.aware-eu.info) working session.
- **Visegrád, Hungary (Apr 2006)**. [AGILE 2006](http://www.agile-secretariat.org/Conference/2006-visegrad/visegrad.html) Conference.
- **Santiago de Cuba, Cuba (Jan 2006)**. [I Jornadas de seguimiento del convenio UJI - UO](http://graficos.uji.es/ujiuo/).
- **Davos, Switzerland (Jan 2006)**. [AWARE](http://www.aware-eu.info) meeting.

---

- **Enschede, The Netherlands (Oct-Dec 2005)**. Research stay at [ITC](http://www.itc.nl).
- **Granada, Spain (Sep 2005)**. [CEDI 2005](http://cedi2005.ugr.es) conference.
- **Copenhagen, Denmark (Aug 2005)**. [DEXA 2005](http://www.dexa.org/dexa/dexa2005/drupal/index71ca.html) conference.
- **East Europe (Aug 2005)**. 2-week holiday through Warsaw-Krakow-Prague-Brno-Bratislava-Budapest by train!
- **Fiesole/Firenze & Milano, Italy (Jul 2005)**. [Vespucci Summer School](http://www.vespucci.org) & Kick-off meeting of [AWARE](http://www.aware-eu.info) project.
- **Venezia, Italy (Feb 2005)**. A weekend on holiday.

---

- **Oslo, Norway (Sep-Dec 2004)**. Research stay at [SINTEF](http://www.sintef.no).
- **Liege, Belgium (Sep 2004)**. Final review of European Project [ACE-GIS](http://www.acegis.net).
- **Zaragoza, Spain (Sep 2004)**. [DEXA 2004](http://www.dexa.org/dexa/dexa2004/index.php?include=main.php) Conference.
- **Fiesole/Firenze, Italy (Jul 2004)**. [Vespucci Summer School](http://www.vespucci.org).
- **Benicassim/Castellón, Spain (Jun 2004)**. [International Postgraduate Course on Geographic Information Technologies](http://edugi.uji.es/).
- **Crete, Greece (Apr 2004)**. [AGILE 2004](http://www.agile-secretariat.org/Conference/greece2004/heraklion.html) Conference.
- **Liege, Belgium (Feb 2004)**. Review of European Project [ACE-GIS](http://www.acegis.net).
